package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var installHookCmd = &cobra.Command{
	Use:   "install-hook",
	Short: "Install Lattice-Shield as a Git pre-commit hook",
	Long: `Install Lattice-Shield as the Git pre-commit hook for the current repository.
Every developer commit will be automatically scanned for secrets.

Run from the repository root:
  lattice-shield install-hook`,
	RunE: runInstallHook,
}

func init() {
	rootCmd.AddCommand(installHookCmd)
}

// hookScript is the shell script written to .git/hooks/pre-commit.
const hookScript = `#!/bin/sh
# Lattice-Shield Pre-Commit Hook
# Auto-generated by: lattice-shield install-hook
# https://github.com/lattice-suite/lattice-shield

STAGED=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED" ]; then
  exit 0
fi

echo ""
echo "  Running Lattice-Shield security check..."
echo ""

# shellcheck disable=SC2086
lattice-shield check $STAGED
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "  ╔══════════════════════════════════════════════════════════╗"
  echo "  ║  COMMIT BLOCKED by Lattice-Shield                        ║"
  echo "  ║  Secrets or API keys were detected in staged files.      ║"
  echo "  ║  Run: lattice-shield anonymize <file>  to sanitize.      ║"
  echo "  ╚══════════════════════════════════════════════════════════╝"
  echo ""
  exit 1
fi

exit 0
`

func runInstallHook(_ *cobra.Command, _ []string) error {
	green := color.New(color.FgGreen, color.Bold)
	yellow := color.New(color.FgYellow, color.Bold)

	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		return fmt.Errorf("no .git directory found — run this command from the root of a Git repository")
	}

	hooksDir := filepath.Join(".git", "hooks")
	if err := os.MkdirAll(hooksDir, 0750); err != nil {
		return fmt.Errorf("cannot create hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")

	if _, err := os.Stat(hookPath); err == nil {
		yellow.Println("  Warning: existing pre-commit hook found — overwriting.")
	}

	if err := os.WriteFile(hookPath, []byte(hookScript), 0750); err != nil {
		return fmt.Errorf("cannot write hook script: %w", err)
	}

	green.Printf("\n  ✓ Pre-commit hook installed at %s\n\n", hookPath)
	fmt.Println("  Every commit in this repository will now be scanned for secrets.")
	fmt.Println("  Use 'git commit --no-verify' to bypass (strongly discouraged).")

	return nil
}
